# conda environment description file for midoss-app package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the midoss-app web app with:
#
#    $ cd midoss-app-dev
#    $ conda env create -f envs/environment-dev.yaml
#    $ source activate midoss-app-dev
#    (midoss-app-dev)$ python3 -m pip install --editable .

name: midoss-app-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - bottleneck
  - dask
  - ipywidgets
  - matplotlib
  - netCDF4
  - pillow
  - pip
  - pyproj
  - pyresample
  - python=3.8
  - pyyaml
  - requests
  - tqdm
  - xarray

  - pip:
    - attrs
    - pyramid
    - pyramid_debugtoolbar
    - pyramid_mako
    - sentry-sdk
    - supervisor
    - waitress
